CREATE DATABASE crudadm;

CREATE TABLE IF NOT EXISTS users(
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR(45) NOT NULL,
	"email" VARCHAR(45) NOT NULL UNIQUE,
	"password" VARCHAR(120) NOT NULL,
	"admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "active" BOOLEAN NOT NULL DEFAULT TRUE
);